from __future__ import annotations

import unittest
from pathlib import Path


class QueueClosureOverviewTests(unittest.TestCase):
    def test_frontend_exposes_queue_closure_overview(self) -> None:
        runtime = (Path(__file__).parents[1] / "bac_analysis_portal" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn("function buildQueueClosureSummary", runtime)
        self.assertIn("function renderQueueClosureOverview", runtime)
        self.assertIn("function renderQueueClosureDeliveryStrip", runtime)
        self.assertIn('class="queue-closure-dock"', runtime)
        self.assertIn('class="queue-batch-actions-mobile"', runtime)
        self.assertIn('class="queue-command-head"', runtime)
        self.assertIn('class="queue-command-controls"', runtime)
        self.assertIn("data-queue-closure-filter", runtime)
        self.assertIn("闭环待办", runtime)
        self.assertIn("交付闭环率", runtime)
        self.assertIn("待业务处置", runtime)
        self.assertIn("异常阻塞", runtime)
        self.assertIn("升级处置", runtime)
        self.assertIn("recent_events", runtime)
        self.assertIn("最近留痕", runtime)
        self.assertIn("delivery_evidence", runtime)
        self.assertIn("交付证据包", runtime)
        self.assertIn("queue-delivery-evidence", runtime)
        self.assertIn("event.detail", runtime)
        self.assertIn("responsibility.separation_verified", runtime)
        self.assertIn("责任分离", runtime)
        self.assertIn("报告复核须由另一名管理员或组管理员签核", runtime)
        self.assertIn("reviewer_unavailable", runtime)
        self.assertIn("缺复核人", runtime)
        self.assertIn("候选复核人", runtime)
        self.assertIn("function renderReviewerReadinessPanel", runtime)
        self.assertIn("个任务缺少合资格复核人", runtime)
        self.assertIn("任务创建人不能复核自己的任务", runtime)
        self.assertIn("只能新增另一名 admin", runtime)
        self.assertIn("data-create-reviewer-role", runtime)
        self.assertIn("Promise.all([adminDomain.refreshUsers(), loadTasks()])", runtime)
        self.assertIn('params.get("admin_section")', runtime)
        self.assertIn('params.get("task")', runtime)
        self.assertIn('params.get("closure_action")', runtime)
        self.assertIn('setActiveTab("queue-tab")', runtime)
        self.assertIn("failure_archived", runtime)
        self.assertIn("stopped_archived", runtime)
        self.assertIn("/failure-disposition", runtime)
        self.assertIn("accept_failure", runtime)
        self.assertIn("accept_stop", runtime)
        self.assertIn("function renderFailureDiagnosisBlock", runtime)
        self.assertIn("异常诊断", runtime)
        self.assertIn("系统诊断用于辅助定位", runtime)
        self.assertIn("diagnosis_category", runtime)
        self.assertIn("function renderClosureNextAction", runtime)
        self.assertIn('actionId === "review_report" && href', runtime)
        self.assertIn(">查看报告</a>", runtime)
        self.assertIn('review_log: "log"', runtime)
        self.assertIn('decide_rebuild: "rebuild"', runtime)
        self.assertIn('open_output: "browse_output"', runtime)
        self.assertIn('import_sample: "import_database"', runtime)
        self.assertIn("comparison_outcome", runtime)
        self.assertIn("需升级复核或处置", runtime)
        self.assertIn("最近样本留痕", runtime)
        self.assertIn("function confirmTaskClosureAction", runtime)
        self.assertIn("function canSignClosureAction", runtime)
        self.assertIn('role === "group_admin" && groupName && taskGroup === groupName', runtime)
        self.assertIn('String(actionId || "").trim() === "review_report"', runtime)
        self.assertIn("canSignClosureAction(task, normalized)", runtime)
        self.assertIn("review_outcome", runtime)
        self.assertIn("需重分析或补充复核", runtime)
        self.assertIn("/closure-actions/", runtime)
        self.assertIn('const CLOSURE_SYNC_STORAGE_KEY = "bac-closure-sync-event"', runtime)
        self.assertIn("function bindClosureSyncEvents", runtime)
        self.assertIn('window.addEventListener("storage"', runtime)
        self.assertIn('window.addEventListener("focus"', runtime)
        self.assertIn('refreshClosureStateFromSignal(event.newValue, "storage")', runtime)
        self.assertIn('refreshClosureStateFromSignal(raw, "focus")', runtime)
        self.assertIn("Promise.all([loadTasks(), loadDatabaseRecords()])", runtime)
        self.assertIn("pendingClosureActionFromUrl", runtime)
        self.assertIn("function consumePendingClosureActionFromUrl", runtime)
        self.assertIn("function focusQueueInspectorSection", runtime)
        self.assertIn("function getClosureActionTargetSelector", runtime)
        self.assertIn('review_report: "报告复核"', runtime)
        self.assertIn('import_sample: "样本入库"', runtime)
        self.assertIn('compare_history: "历史对照"', runtime)
        self.assertIn("已定位到", runtime)
        self.assertIn("data.next_action?.label", runtime)
        self.assertIn("下一步：", runtime)
        self.assertIn("async function importTaskIntoDatabase", runtime)
        self.assertIn("async function submitMetaDatabaseImport", runtime)
        self.assertIn("function showTaskDatabaseImportToast", runtime)
        self.assertIn("function formatTaskDatabaseImportMessage", runtime)
        self.assertIn("function summarizeImportSkippedItems", runtime)
        self.assertIn("成功导入 ${importedCount} 个样本，跳过 ${skippedCount} 个", runtime)
        self.assertIn("失败任务：", runtime)
        self.assertIn("database-trace-cell-actions", runtime)
        self.assertIn("function buildTaskResultPageHref", runtime)
        self.assertIn('params.set("return_to", normalizedReturnTo)', runtime)
        self.assertIn('buildTaskResultPageHref(taskId, { returnTo: "queue" })', runtime)
        self.assertIn('buildTaskResultPageHref(taskId, { returnTo: "database", sampleKey: row?.sample_key || "" })', runtime)
        self.assertIn('const sampleFocus = String(params.get("sample_key") || "").trim()', runtime)
        self.assertIn("pendingDatabaseSampleKeyFromUrl", runtime)
        self.assertIn("function focusPendingDatabaseSampleFromUrl", runtime)
        self.assertIn("database-row-return-focus", runtime)
        self.assertIn('trace.report_href || ""', runtime)
        self.assertIn('href="/workstation?tab=queue&task=${encodeURIComponent(taskId)}"', runtime)
        self.assertGreaterEqual(runtime.count("Promise.all([loadDatabaseRecords(), loadTasks()])"), 2)
        styles = (Path(__file__).parents[1] / "bac_analysis_portal" / "static" / "styles.css").read_text(encoding="utf-8")
        self.assertIn(".database-trace-cell-actions", styles)
        self.assertIn(".database-table tr.database-row-return-focus", styles)
        self.assertIn(".queue-delivery-evidence", styles)
        self.assertIn(".queue-delivery-evidence-grid", styles)
        self.assertIn(".queue-closure-dock", styles)
        self.assertIn("@media (min-width: 1800px)", styles)
        self.assertIn("@media (max-width: 480px)", styles)
        self.assertIn(".queue-command-panel > .queue-closure-overview", styles)
        self.assertIn(".queue-command-head", styles)
        self.assertIn(".queue-command-controls", styles)
        self.assertIn(".queue-console-grid:has(.queue-closure-dock .queue-closure-overview.is-collapsed)", styles)
        self.assertIn("clamp(360px, 16vw, 520px)", styles)
        self.assertIn("grid-template-columns: repeat(4, minmax(0, 1fr))", styles)


if __name__ == "__main__":
    unittest.main()
