set -e
true
true
/home/dell/miniconda3/envs/TB_ONT/bin/spades-core /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K21/configs/config.info /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K21/configs/isolate_mode.info
/home/dell/miniconda3/envs/TB_ONT/bin/spades-core /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K33/configs/config.info /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K33/configs/isolate_mode.info
/home/dell/miniconda3/envs/TB_ONT/bin/spades-core /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K55/configs/config.info /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K55/configs/isolate_mode.info
/home/dell/miniconda3/envs/TB_ONT/bin/spades-core /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/configs/config.info /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/configs/isolate_mode.info
/home/dell/miniconda3/envs/TB_ONT/bin/python /home/dell/miniconda3/envs/TB_ONT/share/spades/spades_pipeline/scripts/copy_files.py /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/before_rr.fasta /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/before_rr.fasta /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/assembly_graph_after_simplification.gfa /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/assembly_graph_after_simplification.gfa /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/final_contigs.fasta /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/contigs.fasta /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/first_pe_contigs.fasta /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/first_pe_contigs.fasta /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/strain_graph.gfa /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/strain_graph.gfa /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/scaffolds.fasta /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/scaffolds.fasta /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/scaffolds.paths /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/scaffolds.paths /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/assembly_graph_with_scaffolds.gfa /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/assembly_graph_with_scaffolds.gfa /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/assembly_graph.fastg /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/assembly_graph.fastg /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/K77/final_contigs.paths /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/contigs.paths
true
/home/dell/miniconda3/envs/TB_ONT/bin/python /home/dell/miniconda3/envs/TB_ONT/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/scaffolds.fasta --misc_dir /data/deploy/meta_genome/Script/Blood/fastq_analysis/Men-IGT/spades_output/misc --threshold_for_breaking_scaffolds 3
true
